[package]
name = "error-code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-code-macros = {workspace=true}
thiserror = {workspace=true}
http = {workspace=true}
base64 = {workspace=true}
